### PR TITLE
event emitted receiving an object

### PR DESCRIPTION
**Pull request by leonprou**
`eventEmitted` and `eventNotEmitted` can receive an object instead a filter

### CODE REVIEW

**Comment by rkalis** [comment]
Hey @leonprou 

Thanks for opening this PR. I like the toFilterFunction function, makes the change very clean 👍

One thing is I think with this convenience form we want to be able to only include the arguments we care about. So for instance if I call
```
truffleAssert.eventEmitted(result, 'Play', { betNumber: 1, winningNumber: 1 });
```

It should succeed even if the full arguments are 
```
{
    player: ..., 
    qid: ..., 
    betSize: ..., 
    betNumber: 1, 
    winningNumber: 1
}
```

What do you think?

**Comment by leonprou** [comment]
@rkalis Yeah I think the same.
Will try to submit the change in the following days

**Comment by rkalis** [comment]
This looks great! Thanks @leonprou, I will look at it a bit more and do some tests this weekend, and then I'll merge.

**Comment by rkalis** [comment]
Looks good, thanks for your contribution. I see you removed the airbnb-base config in eslintrc, but I think that was an accident, so I'll add it back in after merging.

We should still add something about this change in the README.md. If you want to do this, I'll leave this PR open for a bit if you want to add this, but I can also add it to the README myself. Let me know what you prefer, then I'll merge the PR.

**Comment by leonprou** [comment]
@rkalis 

Hey! yeah, changing of eslintrc was by accident. I was having troubles to run the linter locally.

Feel free to change the README, I think you have a better context on this :).

**Pull request merged**
